### PR TITLE
Allow the summary selector to match multiple elements

### LINKED ISSUE #44: Support multiple nodes for summary
I would like to have the summary generated from multiple nodes. I have a case where the root node doesn't result in a good summary, but two child nodes would be a good summary.

Example:

```
[feed.config]
url = "https://rkzbios.nl/"
item = ".MuiGrid-grid-md-12"
heading = "span.MuiTypography-displayBlock"
link = "a"
summary = "div.jss61, div img"
#summary = "a" #this summary would not be displayed nice in my favourite rss reader
```

However, this doesn't work, because only the first match of `summary` (the dates the movie is playing) is included, but not the second match (the movie image).

Supplying the parent of the summary nodes (`summary = "a"`) isnt' a good match, because a lot of whitespace is displayed, and also the whole summary is a link, which I really don't want.

Anyways: would this be a good idea? Thanks for rsspls anyways.

### PR DESCRIPTION
**Pull request by wezm**
All matched elements are used to generate the item description.

Closes #44

### CODE REVIEW

**Comment by wezm** [comment]
@doekman any chance you can test this out to see if it works for you?

**Comment by doekman** [comment]
I got Rust running on my computer. The whole process is friction free (wouldn't expect that from rust, LOL).

The results from all found nodes is included, but they always seems to appear in the DOM order. I would like when I change the order of the selectors, the found elements are also included in this order.

In my example: on the original website, an item first shows an image, and below the image are the title and play dates of the movie. I want to show the play dates first in the summary, and after that the image.

So `summary = "img, div"` should return `<div>...</div>` and `summary = "div, img"` should return `<div>...</div>`.

**Comment by wezm** [comment]
Thanks for testing. I really appreciate that. For the comma based CSS syntax I don't have any control over the order they're matched, since it's done by a library and the behaviour matches browser behaviour. I expect that it traverses the DOM tree and checks if the selector matches (regardless of selector order), yielding matching elements as they are found.

I think in order to support what you need the `summary` value will need to be able to accept a string or an array of strings so something like:

```toml
summary = ["div", "img"]
```

and `rsspls` will make a pass through the document for each selector in the order they're defined.

**Comment by wezm** [comment]
I pushed another commit that allows using an array of selectors. @doekman does this allow you to achieve what you wanted? In your original example from #44 this would be specified as:

```toml
summary = ["div.jss61", "div img"]
```

**Comment by doekman** [comment]
Yes, works nicely. I also like the solution by using an array of selectors!

**Pull request merged**
